services:
  uptime-kuma:
    image: 'louislam/uptime-kuma:1'
    environment:
      - SERVICE_FQDN_UPTIMEKUMA_3001
    volumes:
      - '/opt/my-project/uptime-kuma:/app/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '3001:3001'
    healthcheck:
      test:
        - CMD-SHELL
        - extra/healthcheck
      interval: 2s
      timeout: 10s
      retries: 15
